[package]
name = "com-sandpolis-agent-micro"
version = "0.1.0"
edition = "2018"

[dependencies]
protobuf = { version = "2", features = ["with-bytes"] }
rust-embed = "5.9"
uuid = "0.8"
log = "0.4"
env_logger = "0.8"