on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Install dependencies (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libncursesw5-dev libprotobuf-dev
    - name: Install dependencies (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        brew install protobuf
    - name: Initialize Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Assemble protobuf sources
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assembleProto --no-daemon
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build agent
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --bin agent
    - name: Build boot agent
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --bin bootagent
      if: matrix.os == 'ubuntu-latest'
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-x86_64
        path: target/release/agent
